package asalty.fish.clickhousejpa.annotation;

/**
 * 引擎枚举 自动生成的 我也不知道对不对
 * @author 13090
 */
public enum ClickHouseEngine {
    MergeTree,
    ReplacingMergeTree,
    SummingMergeTree,
    AggregatingMergeTree,
    CollapsingMergeTree,
    ReplacingCollapsingMergeTree,
    SummingCollapsingMergeTree,
    AggregatingCollapsingMergeTree,
    Graphite,
    AggregatingGraphite,
    CollapsingGraphite,
    ReplacingCollapsingGraphite,
    SummingCollapsingGraphite,
    AggregatingCollapsingGraphite,
    SummingGraphite,
    ReplacingGraphite,
    AggregatingGraphiteWithoutRowID,
    CollapsingGraphiteWithoutRowID,
    ReplacingCollapsingGraphiteWithoutRowID,
    SummingCollapsingGraphiteWithoutRowID,
    AggregatingCollapsingGraphiteWithoutRowID,
    SummingGraphiteWithoutRowID,
    ReplacingGraphiteWithoutRowID,
    MergeTreeWithoutRowID,
    ReplacingMergeTreeWithoutRowID,
    SummingMergeTreeWithoutRowID,
    AggregatingMergeTreeWithoutRowID,
    CollapsingMergeTreeWithoutRowID,
    ReplacingCollapsingMergeTreeWithoutRowID,
    SummingCollapsingMergeTreeWithoutRowID,
    AggregatingCollapsingMergeTreeWithoutRowID,
    GraphiteWithoutRowID,
    MergeTreeDictionary,
    ReplacingMergeTreeDictionary,
    SummingMergeTreeDictionary,
    AggregatingMergeTreeDictionary,
    CollapsingMergeTreeDictionary,
    ReplacingCollapsingMergeTreeDictionary,
    SummingCollapsingMergeTreeDictionary,
    AggregatingCollapsingMergeTreeDictionary,
    GraphiteDictionary,
}
