server:
  port: 9001
spring:
  jpa:
    clickhouse:
      driver-class-name: com.github.housepower.jdbc.ClickHouseDriver
      url: jdbc:clickhouse://localhost
      port: 19000
      database: tutorial
      username: default
      password:
      table-update: true
      hikari:
        # 连接池的最大连接数
        maximum-pool-size: 10
        # 空闲超时
        idleTimeout: 1000000
        # 连接超时时间
        connection-timeout: 5000